// <auto-generated />
using Tedd.ShortUrl.Web.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Tedd.ShortUrl.Web.Migrations
{
    [DbContext(typeof(ShortUrlDbContext))]
    [Migration("20171024184811_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tedd.ShortUrl.Web.Models.ShortUrlModel", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatorAccessToken")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("Expires");

                    b.Property<DateTime?>("FirstVisit");

                    b.Property<DateTime?>("LastVisit");

                    b.Property<string>("MetaData");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Key");

                    b.ToTable("ShortUrl");
                });
#pragma warning restore 612, 618
        }
    }
}
